[package]
name = "vga"
version = "0.1.0"
authors = ["mental <m3nta1@yahoo.com>"]
edition = "2018"

[dependencies]
volatile = "0.2.6"
spin = "0.5.2"

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64 = "0.4.1"
cpuio = "0.2.0"

[profile.dev]
panic = "abort"
