[package]
name = "vga"
version = "0.1.0"
authors = ["mental <m3nta1@yahoo.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
volatile = "0.2.6"

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64 = "0.4.1"

[profile.dev]
panic = "abort"
