[package]
name = "kernel"
version = "0.1.0"
authors = ["mental <m3nta1@yahoo.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
vga = { path = "../drivers/vga" }
x86_64 = "0.4.1"

[profile.dev]
panic = "abort"
