[package]
name = "kernel"
version = "0.1.0"
authors = ["mental <m3nta1@yahoo.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
vga = { path = "../drivers/vga" }
x86_64 = "0.4.1"
spin = "0.5.2"
multiboot2 = "0.8.1"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }

[profile.dev]
panic = "abort"
