[package]
name = "kernel"
version = "0.1.0"
authors = ["mental <m3nta1@yahoo.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
# Local deps
vga = { path = "../drivers/vga" }
serial = { path = "../drivers/serial" }
pic = { path = "../drivers/pic" }
# Other deps
linked_list_allocator = "0.6.6"
x86_64 = "0.8.3"
spin = "0.5.2"
multiboot2 = "0.8.1"
bit_field = "0.10.0"
bitflags = "1.2.1"
pc-keyboard = "0.5.0"
pic8259_simple = "0.1.1"
goblin = { version = "0.2.0", features = ["elf64", "elf32"], default-features = false }
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }

[profile.dev]
panic = "abort"
