[package]
name = "mem"
version = "0.0.0"
authors = ["mental <mentalfoss@yahoo.com>"]
edition = "2018"

[dependencies]
# bit_field = "0.10.1"
multiboot2 = "0.10.1"
# tinyvec = "1.1.0"
x86_64 = { version = "0.13" }
