[package]
name = "wasm"
version = "0.1.0"
authors = ["mental <m3nta1@yahoo.com>"]
edition = "2018"

[dependencies]
bare-wasm = { git = "https://github.com/mental32/bare-wasm" }

[profile.dev]
panic = "abort"
